# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
title: Brigitte Castañeda
email: brigittecasro@gmail.com
description: > # this means to ignore newlines until "url:"
  Personal website.
footer_text: > #

url: #"https://brigitte-castaneda.github.io/"
baseurl: #/al-folio # the subpath of your site, e.g. /blog/
last_updated: October 2024 # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: brigitte-castaneda
twitter_username: BrigitteCasRo
linkedin_username: brigittecasro
scholar_authorid: yq_2itUAAAAJ # put your google scholar author id
contact_note: >
  Feel free to drop me a line at k.castaneda{at}uniandes.edu.co

google_analytics: UA-XXXXXXXXX # out your google-analytics code

# Tags
tag_dir: tag

# Edit SASS
sass:
    sass_dir: _sass


# -----------------------------------------------------------------------------
# Site navigation
# -----------------------------------------------------------------------------
nav:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "About"
    url: "/about/"

# -----------------------------------------------------------------------------
# Pagination
# -----------------------------------------------------------------------------
#paginate: 8
#permalink: /articles/:year/:title/
#paginate_path: /articles/page:num/

#text:
#  pagination:
#    newer: 'Newer'
#    older: 'Older'

# -----------------------------------------------------------------------------
# Comments
# -----------------------------------------------------------------------------
disqus_shortname: # put your disqus shortname

# -----------------------------------------------------------------------------
# Optional features
# -----------------------------------------------------------------------------
show_social_icons:  true
enable_anchorjs:    true
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: rouge

# Includes
include: ['_pages']

# Gems
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jemoji


# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.11.1"
anchorjs_version: "3.2.2"
