---
title: "Hola"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Hola
soy __Brigitte Castañeda__

Mírame [aquí](https://github.com/brigitte-castaneda)

---
pagetitle : Home - Brigitte Castañeda


```{r, eval=T , echo=F , message=F , warning=F}
# load packages
require(pacman) # require pacman
p_load(tidyverse,rio,sf,leaflet,viridis, # require and/or install packages
       osmdata, # API Open Street Maps
       ggmap,   # API Google Maps
       ggsn,    # Barras de escalas
       gtools)  # Funcion quantcut


######## 1.1. Descargar datos   ######## 

#=== 1.1.1. Get amenities ===#

# get osm data
osm = opq(bbox = getbb("Cali Colombia")) %>%
  #add_osm_feature(key = "amenity", value = "parking") %>%
  add_osm_feature(key = "amenity", value = "bus_station") %>%
  #add_osm_feature(key = "amenity", value = "stripclub") %>%
  osmdata_sf()
osm %>% class()
osm

# get sf object
amenities = osm$osm_points  %>%  dplyr::select ( c("osm_id", "amenity"))

#=== 1.1.2. Get street ===#
# get osm data
street = opq(bbox = getbb("Cali Colombia")) %>%
  add_osm_feature(key = "highway") %>%
  osmdata_sf()

# get sf object
street = street$osm_lines %>% dplyr::select(osm_id,name)
street = street %>%
  subset(str_detect(name,"Avenida")==T | str_detect(name,"MIO")==T)

#=== 1.1.3. Get Polygons ===#

# get osm data
barrios = opq(bbox = getbb("Cali Colombia")) %>%
  add_osm_feature(key = "place", value = "neighbourhood") %>%
  osmdata_sf()

# get sf object
barrios = barrios$osm_multipolygons %>% dplyr::select(osm_id,name) %>% st_transform(4326)


######## 1.2. Visualizar información   ######## 
leaflet() %>% 
  addTiles() %>% 
  addPolygons(data=barrios, col="red")%>% 
  addPolylines(data=street, weight=1 , col="green") %>% 
  addCircleMarkers(data=amenities, weight=0.3 , col="blue")


```

Este mapa muestra que el huracan **Katrina** tuvo un diámetro máximo de `r max(df$hu_diameter, na.rm=T)` metros. Los datos fueron tomados de la página oficial de [NOAA](https://www.nhc.noaa.gov/data/#hurdat). Por ejemplo la distribución de huracanes a lo largo del tiempo se ve así:


```{r, eval=T , echo=F , message=F , warning=F}
hist(df$year)
```